        ld.b r0, (r3);
        ld.w r2, (sp+2);
        add  r2, r0;
        ld.b r0, (r2);
        or   r1, r0;
        add  r1, r1;
        add  r1, r1;
        addq r3, #-2;
        addq r3, #-2;